---
title: "R Notebook"
output: html_notebook
---
```{r, message=FALSE,warning=FALSE}
library(dplyr)
library(tidyr)
require(foreign)
require(nnet)
library(ipfr)
```


```{r}
df <- read.csv("example_model.csv")
```

```{r}
row1 <- c(1,2,3)
row2 <- c(4,5,6)
row3 <- c(7,8,9)
row4 <- c(10,11,12)
```

```{r}
df <- rbind(df %>% slice(rep(row1,60)),
      df %>% slice(rep(row2,40)),
      df %>% slice(rep(row3,63)),
      df %>% slice(rep(row4,37))) %>%
  mutate(Weight = 1/3) %>%
  select(-Respondents)
```


```{r}
df <- df %>% 
  gather(Type,Infected,-Weight,-Job) %>%
  mutate(Weight = Infected * Weight) %>%
  select(-Infected) %>%
  filter(Weight > 0)
```

```{r}
df %>% 
  group_by(Job,Type) %>%
  summarise(sum(Weight))
```



```{r}
test <- multinom(Type ~ Job, weights = Weight, data = df)
```

```{r}
summary(test)
```




```{r}
jobs <- data.frame(Job = c("A", "B"))
ev <- cbind(jobs,predict(test, newdata = jobs, "probs"))
m <- as.matrix(ev[,2:5])
x <- c(100,100)
y <- c(10,30,85,75)
```

```{r}
sum(y)
```



```{r}
u <- rep(1,length(x))
v <- rep(1,length(y))
for(i in 0:100){
  m <- m * (x %*% t(v)) / (m %*% v %*% t(v))
  m <- m * (u %*% t(y)) / (u %*% t(u) %*% m)
}
```

```{r}
m
```

```{r}
colSums(m)
```


home: 4
leisure: 4
no infection: 188
work: 4

```{r}
m
```




```{r}
save<-as.data.frame(exp(coef(test)))
(save$JobB + save$`(Intercept)`) / save$`(Intercept)`
```


```{r}
ev %>%
  mutate(HomeInfection = HomeInfection * pops,
         NoInfection = NoInfection * pops,
         LeisureInfection = LeisureInfection * pops,
         WorkInfection = WorkInfection * pops)
```

